# Generated by Django 4.2.2 on 2023-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nba_stats',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('min_per_game', models.FloatField()),
                ('ft_attempts', models.FloatField()),
                ('ft_percent', models.FloatField()),
                ('two_point_attempts', models.FloatField()),
                ('two_point_percent', models.FloatField()),
                ('three_point_attempts', models.FloatField()),
                ('three_point_percent', models.FloatField()),
                ('efg_percent', models.FloatField()),
                ('ts_percent', models.FloatField()),
                ('ppg', models.FloatField()),
                ('rpg', models.FloatField()),
                ('apg', models.FloatField()),
                ('spg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('tpg', models.FloatField()),
                ('off_rating', models.FloatField()),
                ('def_rating', models.FloatField()),
            ],
        ),
    ]
